name: Build TWRP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build TWRP
        uses: oshmoun/build-twrp@v1
        with:
          device_name: TECNO-CM5
          twrp_branch: twrp-12.1
          dt_branch: main
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: twrp-image
          path: ${{ github.workspace }}/boot.img
